# Generated by Django 4.0.6 on 2022-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images_avatars/default_avatar.png', null=True, upload_to='images_avatars', verbose_name='Аватар'),
        ),
    ]
